#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

$app = new \Symfony\Component\Console\Application('SQNote', '1.0.0');
$app->add(new \SQNote\Cli\ImportCommand());
$app->run();
